name: acquire-run-pac

on:
  workflow_dispatch:

jobs:
  sample:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: install pac
        shell: pwsh
        run: |
          $pacNuget = "Microsoft.PowerApps.CLI"
          $version = "1.17.5"
          nuget install $pacNuget -Version $version
          
