name: acquire-run-pac

on:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: install pac
        shell: pwsh
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          
      - name: use pac
        shell: pwsh
        run: |
          pac
