name: test-if-pac-on-path
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      - name: add pac to path
        run: |
          echo $env:POWERPLATFORMTOOLS_PACCLIPATH + "\pac\tools" >> $GITHUB_PATH
      - name: execute pac directly
        shell: pwsh
        run: |
          pac help
