name: test-if-pac-on-path
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      - name: execute pac directly
        run: |
          Write-Host $env:POWERPLATFORMTOOLS_PACCLIPATH
