name: test-if-pac-on-path
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      - name: add pac to path
        shell: pwsh
        run: |
          $pac = (Get-Item "$env:POWERPLATFORMTOOLS_PACPATH").Directory.FullName;
          "$pac" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: execute pac directly
        shell: pwsh
        run: |
          pac help
