name: use-pac-from-actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Install Power Platform Actions
        uses: microsoft/powerplatform-actions/actions-install@v1
        with:
          add-tools-to-path: true
      - name: Install Power Platform Actions
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          tenant-id: ${{ secrets.TENANT_ID }}
          app-id: ${{ secrets.APP_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
      - name: execute pac directly
        shell: pwsh
        run: |
          pac auth who