name: use-pac-from-actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Install Power Platform Actions
        uses: microsoft/powerplatform-actions/actions-install@v1
        with:
          add-tools-to-path: true
      - name: create pac auth profile
        shell: pwsh
        run: |
          pac auth create --name temp-for-workflow --url ${{ secrets.ENVIRONMENT_URL }} --applicationId ${{ secrets.APP_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
      - name: use pac
        shell: pwsh
        run: |
          # use pac with the profile created
          pac auth who